
server:
  port: 9090
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mariadb://141.164.58.68:3306/FSQUARE
    username: ficfack
    password: FFvlr!vor2
    driver-class-name: org.mariadb.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  type-aliases-package: com.example.speedom
  mapper-locations: classpath:repository/*.xml
  configuration:
    map-underscore-to-camel-case: true